# 레포지토리 루트에 두기
formatter: markdown table      # 표 형태로 출력

recursive:
  enabled: true                # 재귀 모드
  path: "."                    # 실행 경로
  include-main: true           # 루트 경로의 README 갱신

output:
  file: README.md              # output파일 이름
  mode: inject                 # <!-- BEGIN_TF_DOCS --> 블록만 교체

sort:
  enabled: true
  by: name
